### PR TITLE
Few small changes requested by @adamcolson.

### PR DESCRIPTION
**Pull request by cyphactor**
Issue: https://github.com/reachlocal/reachedge-wordpress-4x-tracking-plugin/issues/4

I made this changes for the various reasons as explained by @adamcolson.

- The title I changed to match the requested slug name of reachlocal-tracking.
  @adamcolson requested calling it just "ReachLocal" but I have concerns with
  doing this because it limits us in terms of adding another wordpress plugin
  in the future for something else.

- The tags we added because the search in wordpress.org seemed poor initially
  so we decided to split up ReachEdge and ReachLocal to aid in partial
  matching.

- The description we modified to make it clearer that this plugin is also used
  for other ReachLocal solutions not just ReachEdge.

### CODE REVIEW

**Comment by cyphactor** [comment]
@jwreachlocal and @adamlcolson please review this pull request and the changes.

**Comment by jwreachlocal** [comment]
:+1:

**Comment by russCloak** [comment]
:+1: Looks good to me

**Comment by adamlcolson** [comment]
We can rename line 1 "ReachLocal - Tracking Code"

**Comment by cyphactor** [comment]
@adamlcolson are we good to go with this?

**Comment by adamlcolson** [comment]
From the copy editing standpoint, yes.

Adam

On Tue, Mar 17, 2015 at 1:26 PM, Andrew De Ponte <notifications@github.com>
wrote:

> @adamlcolson <https://github.com/adamlcolson> are we good to go with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reachlocal/reachedge-wordpress-4x-tracking-plugin/pull/27#issuecomment-82583107>
> .
>



-- 

Adam Colson | *Director of API Development*

ReachLocal, Inc. (NASDAQ: RLOC)

818-274-0260 x1268 | adam.colson@reachlocal.com | @adamc

21700 Oxnard St. | Suite 1600 | Woodland Hills, CA | 91367


[image: logo_200px.jpg]

**Pull request merged**
